# Start with a base Ubuntu 24.10 image
FROM ubuntu:24.10

# Install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    bash \
    ca-certificates \
    net-tools \
    unzip \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform
ENV TERRAFORM_VERSION=1.10.2
RUN curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip \
    && unzip terraform.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform.zip

# Install Helm
ENV HELM_VERSION=3.16.4
RUN curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" -o helm.tar.gz \
    && tar xzf helm.tar.gz --strip-components=1 -C /usr/local/bin linux-amd64/helm \
    && rm helm.tar.gz

# Install Vault
ENV VAULT_VERSION=1.15.4
RUN curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" -o vault.zip \
    && unzip vault.zip \
    && mv vault /usr/local/bin/ \
    && rm vault.zip

# Install kubectl version 1.30.0
ENV KUBECTL_VERSION=1.30.0
RUN curl -LO "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

# Entry point
CMD ["bash"]
